[[redirects]]
  from = "/blog/"
  to = "https://blog.leafphp.dev"

[[redirects]]
  from = "/codelabs/"
  to = "https://codelabs.leafphp.dev"

[[redirects]]
  from = "/docs/"
  to = "/docs/introduction.html"

[[redirects]]
 from = "guide/doc-style-guide.html"
 to = "/docs/contributing/doc-style-guide.html"

[[redirects]]
  from = "/docs/writing-guide.html"
  to = "/docs/contributing/writing-guide.html"
